server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authapp_db
    username: root
    password: "feedmeMORE1@2$"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        formal_sl: true
    show-sql: true
  